---
- name: CentOS 7 Base
  hosts: all

  tasks:
    - name: Install Java and utilities
      yum:
        name:  '{{ item }}'
        state: present
      with_items:
        - bind-utils
        - java-1.8.0-openjdk-devel
        - net-tools
        - telnet
        - tree
        - unzip
        - wget

    - name: Add JAVA_HOME to the system bashrc file
      lineinfile:
        path: /etc/bashrc
        regexp: '^export\s+JAVA_HOME=.*'
        line: export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:/bin/java::")

...