Vagrant.configure('2') do |config|
  config.vm.box = 'centos/7'
  config.vm.hostname = 'centos-base'

  config.vm.define 'centos-base'
  config.vm.provider 'virtualbox' do |v|
    v.name = 'CentOS 7 Base'
    v.cpus = 2
    v.memory = 4096
  end

  config.vm.provision 'ansible_local' do |ansible|
    ansible.compatibility_mode = '2.0'
    ansible.playbook = 'centos-base-playbook.yml'
    ansible.become = true
  end

end
