---
- block:
  # Remove extraneous profiles
  - name: Remove the Gateway profiles
    file:
      path: '{{ jboss_fuse_home }}/fabric/import/fabric/profiles/gateway/'
      state: absent

  - name: Remove the Insight profiles
    file:
      path: '{{ jboss_fuse_home }}/fabric/import/fabric/profiles/insight/'
      state: absent

  - name: Remove the JBoss profiles
    file:
      path: '{{ jboss_fuse_home }}/fabric/import/fabric/profiles/jboss/'
      state: absent

  - name: Remove the DOSGi profile
    file:
      path: '{{ jboss_fuse_home }}/fabric/import/fabric/profiles/feature/dosgi.profile/'
      state: absent

  - name: Remove the Autoscale profile
    file:
      path: '{{ jboss_fuse_home }}/fabric/import/fabric/profiles/autoscale.profile/'
      state: absent

  - name: Remove the Openshift profile
    file:
      path: '{{ jboss_fuse_home }}/fabric/import/fabric/profiles/openshift.profile/'
      state: absent

  - name: Remove the Unmanaged profile
    file:
      path: '{{ jboss_fuse_home }}/fabric/import/fabric/profiles/unmanaged.profile/'
      state: absent

- name: Configure logging in the default Karaf profile
  template:
    src: profiles/org.ops4j.pax.logging.j2
    dest: '{{ jboss_fuse_home }}/fabric/import/fabric/profiles/karaf.profile/org.ops4j.pax.logging.properties'
    owner: '{{ jboss_fuse_user }}'
    group: '{{ jboss_fuse_group }}'

- name: Install the custom Fabric8 container profiles
  copy:
    src: profiles/{{ item }}
    dest: '{{ jboss_fuse_home }}/fabric/import/fabric/profiles'
    owner: '{{ jboss_fuse_user }}'
    group: '{{ jboss_fuse_group }}'
  with_items:
    - base
    - container
    - deployment
    - splunk

- name: Configure logging in the base Karaf profile
  template:
    src: profiles/org.ops4j.pax.logging.j2
    dest: '{{ jboss_fuse_home }}/fabric/import/fabric/profiles/base/karaf.profile/org.ops4j.pax.logging.properties'
    owner: '{{ jboss_fuse_user }}'
    group: '{{ jboss_fuse_group }}'

- name: Configure the Splunk HTTP Client profile
  template:
    src: profiles/splunk/default-client.xml.j2
    dest: '{{ jboss_fuse_home }}/fabric/import/fabric/profiles/splunk/default_client.profile/default-client.xml'
    owner: '{{ jboss_fuse_user }}'
    group: '{{ jboss_fuse_group }}'

- name: Configure the Splunk Karaf JMX profile
  template:
    src: profiles/splunk/karaf/{{ item }}.xml.j2
    dest: '{{ jboss_fuse_home }}/fabric/import/fabric/profiles/splunk/karaf_jmx.profile/{{ item }}.xml'
    owner: '{{ jboss_fuse_user }}'
    group: '{{ jboss_fuse_group }}'
  with_items:
    - jmx-attribute-change-monitors
    - jmx-notification-listeners

- name: Configure the Splunk ActiveMQ JMX profile
  template:
    src: profiles/splunk/activemq/{{ item }}.xml.j2
    dest: '{{ jboss_fuse_home }}/fabric/import/fabric/profiles/splunk/activemq_jmx.profile/{{ item }}.xml'
    owner: '{{ jboss_fuse_user }}'
    group: '{{ jboss_fuse_group }}'
  with_items:
    - jmx-attribute-change-monitors

- name: Configure the Splunk ActiveMQ JMS profile
  template:
    src: profiles/splunk/activemq/{{ item }}.xml.j2
    dest: '{{ jboss_fuse_home }}/fabric/import/fabric/profiles/splunk/activemq_jms.profile/{{ item }}.xml'
    owner: '{{ jboss_fuse_user }}'
    group: '{{ jboss_fuse_group }}'
  with_items:
    - jms-consumers

- name: Configure the Splunk Camel JMX profile
  template:
    src: profiles/splunk/camel/{{ item }}.xml.j2
    dest: '{{ jboss_fuse_home }}/fabric/import/fabric/profiles/splunk/camel_jmx.profile/{{ item }}.xml'
    owner: '{{ jboss_fuse_user }}'
    group: '{{ jboss_fuse_group }}'
  with_items:
    - jmx-attribute-change-monitors

- name: Create the fabric
  command: '{{ jboss_fuse_home }}/bin/client "fabric:create --wait-for-provisioning"'
  args:
    creates: '{{ jboss_fuse_home }}/data/zookeeper'


- name: Pause for the Fabric8 initialization
  pause:
    seconds: 30

- name: Restart JBoss Fuse
  service:
    name: '{{ jboss_fuse_id }}'
    state: restarted

- name: Pause while the root container is restarting
  pause:
    seconds: 30
...