---
- name: Create the JBoss Fuse group
  group:
    name:  '{{ jboss_fuse_user }}'

- name: Create the JBoss Fuse user
  user:
    name:  '{{ jboss_fuse_user }}'
    shell: /bin/bash
    group: '{{ jboss_fuse_group }}'

- name: Create a link to the shared maven configuration directory
  file:
    src: /home/vagrant/.m2
    dest: /home/{{ jboss_fuse_user }}/.m2
    state: link
    force: yes
    owner: '{{ jboss_fuse_user }}'
    group: '{{ jboss_fuse_group }}'

- name: Add the vagrant user to the JBoss Fuse group
  user:
    name: vagrant
    groups: '{{ jboss_fuse_group }}'
    append: yes

- name: Check for existing installation
  stat:
    path: '{{ jboss_fuse_home }}'
  register: jboss_fuse_home_stat

- block:
  - name: Expand the JBoss Fuse installation archive
    unarchive:
      src: '{{ item }}'
      dest: /opt/
      owner: '{{ jboss_fuse_user }}'
      group: '{{ jboss_fuse_group }}'
    with_fileglob:
      - files/jboss-fuse-*.zip

  - name: Rename the installation directory
    shell: mv /opt/jboss-fuse-* {{ jboss_fuse_home }}
    args:
      creates: '{{ jboss_fuse_home }}'
  when: jboss_fuse_home_stat.stat.isdir is not defined

- block:
  # Remove unnecessary files
  - name: Removed the unnecessary DOS bat files from the bin directory
    file:
      path: '{{ jboss_fuse_home }}/bin/{{ item }}'
      state: absent
    with_items: '{{ jboss_fuse_bat_files }}'

- block:
  # Configure bin/setenv
  - name: Set the minimum heap size in the setenv script
    lineinfile:
      path: '{{ jboss_fuse_home }}/bin/setenv'
      regexp: '^JAVA_MIN_MEM='
      line: 'JAVA_MIN_MEM=512M'

  - name: Set the maximum heap size in the setenv script
    lineinfile:
      path: '{{ jboss_fuse_home }}/bin/setenv'
      regexp: '^JAVA_MAX_MEM='
      line: 'JAVA_MAX_MEM=512M'

  - name: Remove permgen settings from the setenv script
    lineinfile:
      path: '{{ jboss_fuse_home }}/bin/setenv'
      regexp: '_PERM_MEM'
      state: absent

- name: Configure etc/user.properties file
  ini_file:
    path: '{{ jboss_fuse_home }}/etc/users.properties'
    section: ''
    option: '{{ item }}'
    value: '{{ item }},admin,manager,viewer,Monitor, Operator, Maintainer, Deployer, Auditor, Administrator, SuperUser'
  with_items:
    - admin
    - pronoia

- name: Configure etc/system.properties
  ini_file:
    path: '{{ jboss_fuse_home }}/etc/system.properties'
    section: ''
    option: '{{ item.property }}'
    value: '{{ item.value }}'
  with_items:
    - property: karaf.name
      value: '{{ karaf_root_container_name }}'
    - property: profiles
      value: container-ensemble
    - property: org.osgi.service.http.port
      value: '{{ jboss_fuse_root_container_ports.http }}'

- name: Configure etc/org.ops4j.pax.web.cfg
  ini_file:
    path: '{{ jboss_fuse_home }}/etc/org.ops4j.pax.web.cfg'
    section: ''
    option: '{{ item.property }}'
    value: '{{ item.value }}'
  with_items:
    - property: org.osgi.service.http.port
      value: '{{ jboss_fuse_root_container_ports.http }}'
    - property: org.osgi.service.http.port.secure
      value: '{{ jboss_fuse_root_container_ports.https }}'

- name: Configure etc/org.apache.karaf.shell.cfg
  ini_file:
    path: '{{ jboss_fuse_home }}/etc/org.apache.karaf.shell.cfg'
    section: ''
    option: sshPort
    value: '{{ jboss_fuse_root_container_ports.ssh }}'

- name: Configure etc/org.apache.karaf.management.cfg
  ini_file:
    path: '{{ jboss_fuse_home }}/etc/org.apache.karaf.management.cfg'
    section: ''
    option: '{{ item.property }}'
    value: '{{ item.value }}'
  with_items:
    - property: rmiRegistryPort
      value: '{{ jboss_fuse_root_container_ports.jmx_rmi_registry }}'
    - property: rmiServerPort
      value: '{{ jboss_fuse_root_container_ports.jmx_rmi_server }}'

- name: Configure etc/org.ops4j.pax.logging.cfg
  template:
    src: org.ops4j.pax.logging.cfg.j2
    dest: '{{ jboss_fuse_home }}/etc/org.ops4j.pax.logging.cfg'
    owner: '{{ jboss_fuse_user }}'
    group: '{{ jboss_fuse_group }}'

- block:
  # Setup JBoss Fuse as a service
  - name: Setup the systemd service conf file
    template:
      src: jboss-fuse.conf.j2
      dest: '{{ jboss_fuse_home }}/etc/jboss-fuse.conf'
      owner: root
      group: root

  - name: Setup the systemd service files
    template:
      src: '{{ item }}.j2'
      dest: /etc/systemd/system/{{ item }}
      owner: root
      group: root
    with_items:
      - jboss-fuse.service
      - jboss-fuse@.service

- name: Enable the JBoss Fuse service
  service:
    name: jboss-fuse
    enabled: yes

- name: Start the JBoss Fuse root container
  service:
    name: jboss-fuse
    state: started
...